name: dice_guessing_game
description: A beautiful dice guessing game with animations and sound effects.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your sound files here
  # assets:
  #   - assets/sounds/click.mp3
  #   - assets/sounds/dice_roll.mp3
  #   - assets/sounds/win.mp3
  #   - assets/sounds/lose.mp3